### ISSUE TITLE
set up postgres db for user without sudo privileges

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/ansible-role-aiida#10]
# Problem
Currently, the aiida role sets up the database using the `postgres` user
https://github.com/marvel-nccr/quantum-mobile/blob/1a23171c38fa421653093ef29fc9e03112ef270f/roles/aiida/tasks/aiida-core.yml#L19-L31

This doesn't work, if the user `regularuser` that ansible takes for provisioning does not have sudo privileges.

# Possible solutions
1. Set the password of the `postgres` user and provide it to the role via a variable (should work)
  The problem: `regularuser` won't be able to make any changes to the DB!

2. Install DB using `regularuser` - after all, it's really more of a per-user DB than a system-wide DB.

@giovannipizzi What do you say?

**Comment by giovannipizzi** [comment]
Not sure... Is there an easy way to support both behaviours and choose them with a config flag?

**Comment by ltalirz** [comment]
Many roles anyhow require sudo access currently (the aiida role as well).
So, I'm not sure this is really an issue at the moment. I'm going to close.
