### ISSUE TITLE
Set up of Siesta code is wrong.

### ISSUE THREAD

**Issue by bosonie** [marvel-nccr/ansible-role-aiida#42]
Not even sure if the issue is here, but the code `siesta-v4.1-rc1-siesta` available from the aiida set up in the quantum mobile (last version at least) contains a wrong remote absolute path. It shows `local/Obj` instead of `local/bin`.
This makes aiida_siesta unusable in the quantum mobile.

**Comment by ltalirz** [comment]
ok, thanks for reporting!
would you mind making a PR to fix the role?

Edit: Indeed, the validation of file paths for codes is a contentious issue https://github.com/aiidateam/aiida-core/issues/868 but here it would have helped

**Comment by bosonie** [comment]
Sorry @ltalirz but I have no idea about the mechanism.
Is it here?
https://github.com/marvel-nccr/ansible-role-siesta/blob/ab36d895eba05504d0ede8589ff9fbb6ca862148/defaults/main.yml#L26

When you install siesta, the executable is in the Obj folder of the siesta package. However in the quantum mobile all the executables seem to be in /usr/local/bin. I guess you copy them automatically after installation.

**Comment by ltalirz** [comment]
Indeed - I see the executables are now copied one by one https://github.com/marvel-nccr/ansible-role-siesta/blob/ab36d895eba05504d0ede8589ff9fbb6ca862148/tasks/main.yml#L81-L132 (I guess this was introduced by Alberto).

Simply removing the /Obj postfix should resolve the issue.

**Comment by bosonie** [comment]
...mmm... I'm not understanding. The siesta executable is in the folder /usr/local/bin, so I think everything is correct from the siesta role. The problem comes in the setting up of the code in aiida. Is it done here:
https://github.com/marvel-nccr/ansible-role-aiida/blob/9ee58f9cc59f7850d1d5d67fb5b7ca707481c205/tasks/plugins/aiida-siesta.yml#L13-L26
The item.name is correct. What is the item.folder? I'm very confused

**Comment by ltalirz** [comment]
> What is the item.folder? 

This: https://github.com/marvel-nccr/ansible-role-siesta/blob/ab36d895eba05504d0ede8589ff9fbb6ca862148/defaults/main.yml#L26 ;-)

**Comment by bosonie** [comment]
Ok, now I understood. So this `folder` is not used in the task of the siesta-role, but it is used by the aiida-role. Ok. I'll fix it.
Cheers!
