### ISSUE TITLE
issues with aiida-siesta

### ISSUE THREAD

**Issue by chrisjsewell** [marvel-nccr/ansible-role-aiida#43]
as reported by @bosonie:

> Dear all,
> I found few issues to run aiida_siesta in the quantum mobile (blame on me that I never checked before), I prepared a simple     set of instructions to make the life easy if anyone wants to try for real aiida_siesta in the quantum mobile.

> In order to run aiida_siesta, a new code needs to be installed.

> verdi code setup

> Label: siesta-v4.1-rc1-siesta-bis
    Description []: siesta vv4.1-rc1, but now with right path
    Default calculation input plugin: siesta.siesta
    Installed on target computer? [True]: 
    Computer: localhost
    Remote absolute path: /usr/local/bin/siesta
    Prepend text    ulimit -s unlimited

> In order to explore the functionalities exposed in the video (not in last release of aiida_siesta)

> git clone https://github.com/albgar/aiida_siesta_plugin.git
    cd aiida_siesta_plugin
    pip install -e .
    reentry scan
    verdi daemon restart

> In order to try out the "protocol system".

> wget https://icmab.es/leem/SIESTA_MATERIAL/tmp_PseudoDojo/nc-sr-04_pbe_standard-psf.tgz
   wget https://icmab.es/leem/SIESTA_MATERIAL/tmp_PseudoDojo/nc-sr-04_pbe_stringent-psf.tgz
   tar -xf nc-sr-04_pbe_stringent-psf.tgz
   tar -xf nc-sr-04_pbe_standard-psf.tgz
   verdi data psf uploadfamily nc-sr-04_pbe_stringent-psf nc-sr-04_pbe_stringent-psf "Scalar Relativistic psf strinegnt"
   verdi data psf uploadfamily nc-sr-04_pbe_standard-psf nc-sr-04_pbe_standard-psf "Scalar Relativistic psf"

> Maybe you have a place where you store these information. Otherwise just keep them as a reference in case you get some questions on it.

**Comment by bosonie** [comment]
The code bug was reported and fixed in #42 . The rest is due to aiida_siesta not having a recent release.
