### ISSUE TITLE
Fix systemd templates for profile name with dashes

### ISSUE THREAD

**Issue by chrisjsewell** [marvel-nccr/ansible-role-aiida#51]
When a profile name included dashes (e.g. my-profile), the dashes were replaced by slashes in the systemd unit files for the AiiDA daemon / the REST API, resulting in an error upon start (profile "my/profile" not found).

Note #49 was merged to fix this, however, it was found to be faulty and reverted in #50

**Comment by chrisjsewell** [comment]
@ltalirz are sure this is an issue?
I don't see any problem in https://github.com/marvel-nccr/ansible-role-aiida/pull/62

```console
root@instance:/# systemctl --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

root@instance:/# systemctl --type=service
UNIT                                  LOAD   ACTIVE SUB     DESCRIPTION                                            
aiida-daemon@name-with-dashes.service loaded active running AiiDA daemon service for profile name-with-dashes
...
```

perhaps it is only for an older version of sytemd?

**Comment by ltalirz** [comment]
#50 didn't exactly revert #49 - before #49, there was a mix of %i and %I which lead to the issue (I noticed it on ubuntu 18.04).
The idea would be that after #50 it should be fixed, i.e. if you confirm it's working we can close this

**Comment by chrisjsewell** [comment]
Ok brilliant ta, yep definitely looks to be fixed then
(I didn't know because you never answered my question 😜 https://github.com/marvel-nccr/ansible-role-aiida/pull/50#issuecomment-720504069)
