### ISSUE TITLE
Relevance of aiida-examples.yml?

### ISSUE THREAD

**Issue by chrisjsewell** [marvel-nccr/ansible-role-aiida#58]
@ltalirz are these example repositories still relevant?

- https://github.com/aiidateam/aiida-max-examples.git
- https://github.com/aiidateam/aiida_demos.git

Both have not been updated for over a year.
Plus, I note in the actual release instructions, currently it says: "delete examples/ icon on desktop"

I think its definitely a good idea to have some example notebooks for people to load, especially since now there is a launch button for Jupyter Lab 😄 

![image](https://user-images.githubusercontent.com/2997570/100854010-bb72ed80-3488-11eb-9373-fd1d60c797e7.png)

These notebooks though should be somewhere where they are actively kept up-to-date though, probably ideally in separate branches for each aiida-core version, to ensure they match with the aiida-core installed (e.g. `1.4`, `1.5`, `2.0`, etc)

Perhaps in some way this could be linked with https://github.com/aiidateam/aiida-tutorials

**Comment by chrisjsewell** [comment]
Oh and as a note to self, these notebooks should have metadata pointing to the `aiida` kernel NOT the default `python3` kernel (i.e. using the aiida virtual environment)

**Comment by ltalirz** [comment]
These "aiida max examples" were an early attempt in the "common workflows" direction and were not maintained after this.
I agree to remove them.

**Comment by ltalirz** [comment]
Just dropped the final trace of this in https://github.com/marvel-nccr/ansible-role-aiida/pull/76
