### ISSUE TITLE
Conflict due to new versions of jupyter-client

### ISSUE THREAD

**Issue by bosonie** [marvel-nccr/ansible-role-aiida#74]
This role installs `ipykernel`. The package  `jupyter-client` is a dependence of `ipykernel`. New versions of `jupyter-client` (>=7.0.0) now depend on `nest-asyncio>=1.5` which is incompatible with `plumpy` since the latter requires `nest_asyncio~=1.4.0`.
Now...is `plumpy` working with `nest-asyncio>=1.5`? I am always confused by the meaning of `~=`. It should allow any version that is not a major version change, right? In any case, at the moment, pip complains  `jupyter-client 7.0.3 has requirement nest-asyncio>=1.5, but you have nest-asyncio 1.4.3.` and the build of the quantum mobile fails.
What is the best solution? Downgrade  `jupyter-client`?

**Comment by ltalirz** [comment]
Sorry that this issue never got a reply.
The current aiida-core `main` branch seems to work with `nest-asyncio 1.5.5`
https://github.com/aiidateam/aiida-core/blob/f2c0f2c9258547356467f7e8b320d2cc6be4685b/requirements/requirements-py-3.9.txt#L75

I.e. I believe this issue can be closed.
